notes/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from notes import views


urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^category/(\d+)/$', views.category_view, name='category_view'),
    url(r'^search/$', views.search_view, name='search_view'),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/models.py
import os

from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.utils.translation import ugettext as _


class Category(models.Model):
    title = models.CharField(max_length=64, unique=True)
    icon = models.ImageField(null=True, blank=True)

    def __str__(self):
        return '%s' % self.title

    class Meta:
        ordering = ['title']
        verbose_name = _('category')
        verbose_name_plural = _('categories')


@receiver(models.signals.post_delete, sender=Category)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.icon:
        if os.path.isfile(instance.icon.path):
            os.remove(instance.icon.path)


@receiver(models.signals.post_delete, sender=Category)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `MediaFile` object is updated
    with new file.
    """
    if not instance.pk:
        return False

    try:
        old_file = sender.objects.get(pk=instance.pk).icon
    except sender.DoesNotExist:
        return False

    # new_file = instance.picture
    if old_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)


class Note(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=64, unique=True)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.title, self.category.title)

    class Meta:
        ordering = ['id']
        verbose_name = _('note')
        verbose_name_plural = _('notes')

notes/views.py
from django.shortcuts import render, redirect
from notes.models import Category, Note
from django.views.decorators.csrf import csrf_protect


def index_view(request):
    categories = Category.objects.all()
    last_notes = Note.objects.all().reverse()[:10]
    return render(request, "notes/index.html", {'categories': categories, 'notes': last_notes})


def category_view(request, cid):
    categories = Category.objects.all()
    cat_title = categories.get(id=cid).title
    notes = Note.objects.filter(category_id=cid)
    return render(request, "notes/category_view.html", dict(categories=categories, notes=notes, cat_title=cat_title))


@csrf_protect
def search_view(request):
    if request.POST and request.POST['search'] != '':
        notes = Note.objects.filter(content__contains=request.POST['search']) or Note.objects.filter(
            title__contains=request.POST['search'])
        return render(request, "notes/search.html",
                      dict(categories=Category.objects.all(), notes=notes, my_search=request.POST['search']))
    else:
        return redirect('/')

templates/notes/base.html
{% load staticfiles %}
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<html>
    <head>
        <title>NOTES</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'notes/css/style.css' %}" rel="stylesheet" type="text/css">
        <script src="{% static 'notes/jquery/jquery.min.3.3.1.js' %}"></script>
        <script src="{% static 'notes/javascript/main.js' %}"></script>
        <script src="{% static 'notes/jquery/jquery.sidenav.js' %}"></script>
        {% block head %} {% endblock head %}
    </head>
    <body>

    </body>
</html>

templates/notes/category_view.html
{% extends 'notes/index.html' %}

{% block page_title %}Notes > {{ cat_title }}{% endblock page_title %}
{% block cat_title %} {{ cat_title }} {% endblock cat_title %}

templates/notes/index.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block page_title %}NOTES{% endblock page_title %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'notes/css/style.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'notes/css/switch-check.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'notes/css/sticky-search-bar.css' %}" rel="stylesheet" type="text/css">
        <script src="{% static 'notes/jquery/jquery.min.3.3.1.js' %}"></script>
        <script src="{% static 'notes/javascript/main.js' %}"></script>
        <script src="{% static 'notes/jquery/jquery.sidenav.js' %}"></script>
        {% block head %}{% endblock head %}
    </head>
    <script>
    $(document).ready(function(){
        {% for note in notes %}
            $("#{{ note.id }}note-title").click(function(){
                $("#{{ forloop.counter0 }}note-content").fadeToggle(200);
            }
            );
        {% endfor %}
    });
    </script>

    <body>
        <div id="navbar">
            <form id="form" class="example" action="{% url 'search_view' %}" method="POST"> {% csrf_token %}
                <input type="text" placeholder="Search.." name="search" required>
                <button type="submit"><i>SearchMe!</i></button>
            </form>
        </div>
        <label class="switch">
            <input type="checkbox" checked id="close">
            <span class="slider"></span>
        </label>
        <div class="sidenav" id="sidenav">
            <div id="category" onclick="document.location.href='/'">
                {% csrf_token %}
                <div id="cat-link">Home Page</div>
            </div>
            {% for cat in categories %}
                <div id="category" onclick="document.location.href='{% url 'category_view' cat.id %}'">
                    <div id="icon">
                        {% if cat.icon %}
                            <img src="{{ cat.icon.url }}">
                        {% else %}
                            <img src="{% static 'notes/images/no-image.jpeg' %}" title="no icon">
                        {% endif %}
                    </div>
                    <div id="cat-link">
                        {{ cat.title }}({{ cat.note_set.all.count }})
                    </div>
                </div>
            {% endfor %}
            {% block sidenav %}{% endblock sidenav %}
        </div>

        <div class="main" id="main">
            <h5>{% block cat_title %} Last Notes {% endblock cat_title %}</h5>
            <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Filter title notes.." title="Type in a text">
            <ul id="myUL">
                {% for note in notes %}
                    <li id="{{ note.id }}note-title">
                       <div>
                           {{ forloop.counter }}. {{ note.title }}
                           <span style="color: cadetblue; font-size: 10px">
                               {% if cat_title %}
                                   [{{ note.date|date }}]
                               {% else %}
                                   [{{ note.category.title }}]
                               {% endif %}
                            </span>
                       </div>
                    </li>
                    <span hidden id="{{ forloop.counter0 }}note-content">{{ note.content | linebreaks}}</span>
                {% endfor %}
            </ul>
            {% block main %}{% endblock main %}
        </div>
    {% block content %}{% endblock content %}
    </body>
</html>

templates/notes/search.html
{% extends 'notes/index.html' %}

{% block page_title %}Notes > Search {{ my_search }}{% endblock page_title %}
{% block cat_title %}Search > {{ my_search }} {% endblock cat_title %}